import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import { AuthWrapper } from '@/components/authWrapper'
import {theme} from '@/clientSide/theme'
import { ThemeProvider } from '@mui/material'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en'>
            <AuthWrapper>
                <ThemeProvider theme={theme}>
                    {/* <Navbar /> */}
                    <body className={inter.className}>{children}</body>
                </ThemeProvider>
            </AuthWrapper>
        </html>
    )
}
